kind: CodeInterpreterConfig
apiVersion: v1
metadata:
  name: code-interpreter
spec:
  logging:
    logLevel: 1 # 0: debug, 1: info, 2: warn, 3: error
    useISO8601DateFormat: true
  kernel:
    name: java # This should match with kernel name specified during Kernel installation in Dockerfile
    port: 6000
    isAsynchronousExecutionSupported: false
  healthProbe: # It will respond back /health endpoint with 200 status code if the container is healthy
    endpoint: /health
    successfulHealthCheckThresholdSeconds: 120 # If no health check success in this time, then container will be considered as unhealthy
    initialDelaySeconds: 10 # Time to wait before starting liveness checks (seconds)
    periodSeconds: 15 # Time between code checks (seconds)
    timeoutSeconds: 15 # Timeout for each code check (seconds)
    failureThreshold: 3 # Number of failures before considering the container as failed
    code: 1+1
  codeExecution:
    enableAutoBase64Decoding: false
    defaultTimeoutSeconds: 120
    # synchronousExecution:
    #   preCodeInjectionSnippet: |
    #     System.out.println("Synchronous Execution Started");
    #   postCodeInjectionSnippet: |
    #     System.out.println("Synchronous Execution Completed");
  fileOperation:
    maxUploadFileSizeLimitInMBs: 250
    dataDirectoryPath: /mnt/data
