kind: CodeInterpreterConfig
apiVersion: v1
metadata:
  name: code-interpreter
spec:
  logging:
    logLevel: 1 # 0: debug, 1: info, 2: warn, 3: error
    useISO8601DateFormat: false
  kernel:
    enabled: true
    isFirstParty: true
    name: python3 # This should match with kernel name specified during Kernel installation in Dockerfile
    port: 6000
    runInitScript: true
    kernelInit:
      synchronous:
        enabled: true
        initCommonLibraries: true
        initialDelaySeconds: 2
        periodSeconds: 1
      synchronousWithEmptyKernel:
        enabled: true
        initCommonLibraries: false
        initialDelaySeconds: 2
        periodSeconds: 1
      asynchronous:
        enabled: true
        initCommonLibraries: true
        initialDelaySeconds: 2
        periodSeconds: 1
        initLibrariesFile: "/app/scripts/initialize_libraries_async.py"
  healthProbe: # It will respond back /health endpoint with 200 status code if the container is healthy
    initialDelaySeconds: 0
    code: 1+1
    expectedResult: 2
    commonLibrariesInitTimeoutSeconds: 90
    tikaServer:
      enabled: false
  codeExecution:
    enableAutoBase64Decoding: true
  fileOperation:
    maxUploadFileSizeLimitInMBs: 250
    enableFullPathAccess: false
  initLibrariesFile: "/app/scripts/initialize_libraries.py"
